### ISSUE TITLE
How to install with conda-forge environment.yml

### ISSUE THREAD

**Issue by westurner** [voneiden/ocp-freecad-cam#35]
Here's an environment.yml adapted from an environment.yml for a devcontainer for just build123d with ocp_vscode:

```yaml
# environment.yml for CAD with Python, build123d, cadquery, freecad, ocp_vscode, jupyter-cadquery

channels:
  - conda-forge
  #- defaults
dependencies:
  - build123d
  - cadquery
  - freecad
  - ipykernel
  - ruff
  - pip
  - pip:
    - ocp_vscode
    - jupyter-cadquery
```

```sh
$ mamba install -f environment.yml
#$ mamba env update -f environment.yml
```

References:

- https://github.com/westurner/workboard/blob/main/.devcontainer/devcontainer.json
  - https://github.com/westurner/workboard/blob/main/Dockerfile
    - https://github.com/westurner/workboard/blob/main/environment.yml
